[package]
name = "k_means"
version.workspace = true
edition.workspace = true

[dependencies]
half.workspace = true
rand.workspace = true

base = { path = "../base" }
common = { path = "../common" }
smawk = "0.3.2"

[lints]
workspace = true
