[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
parking_lot.workspace = true
rand.workspace = true

base = { path = "../base" }
common = { path = "../common" }

[lints]
workspace = true
